apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: mudashir/my-backend-movie-app:1.0
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: database-url
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: app-version
          volumeMounts:
            - name: secrets-volume
              mountPath: /etc/secrets
        volumes:
          - name: secrets-volume
            secret:
              secretName: my-secret

          # ...





---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP  # Adjust the service type as needed


