apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: mudashir/my-backend-movie-app:1.0
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: password
          # ...







apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP  # Adjust the service type as needed


apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>


apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  api_key: your-api-key
  other_config: some-value
